
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (02, 'Albacete');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (03, 'Alicante/Alacant');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (04, 'Almería');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (01, 'Araba/Álava');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (33, 'Asturias');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (05, 'Ávila');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (06, 'Badajoz');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (07, 'Balears, Illes');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (08, 'Barcelona');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (48, 'Bizkaia');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (09, 'Burgos');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (10, 'Cáceres');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (11, 'Cádiz');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (39, 'Cantabria');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (12, 'Castellón/Castelló');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (13, 'Ciudad Real');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (14, 'Córdoba');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (15, 'Coruña, A');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (16, 'Cuenca');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (20, 'Gipuzkoa');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (17, 'Girona');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (18, 'Granada');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (19, 'Guadalajara');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (21, 'Huelva');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (22, 'Huesca');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (23, 'Jaén');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (24, 'León');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (25, 'Lleida');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (27, 'Lugo');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (28, 'Madrid');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (29, 'Málaga');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (30, 'Murcia');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (31, 'Navarra');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (32, 'Ourense');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (34, 'Palencia');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (35, 'Palmas, Las');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (36, 'Pontevedra');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES (26, 'Rioja, La');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES ('37', 'Salamanca');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES ('38', 'Santa Cruz de Tenerife');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES ('40', 'Segovia');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES ('41', 'Sevilla');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES ('42', 'Soria');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES ('43', 'Tarragona');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES ('44', 'Teruel');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES ('45', 'Toledo');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES ('46', 'Valencia/València');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES ('47', 'Valladolid');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES ('49', 'Zamora');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES ('50', 'Zaragoza');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES ('51', 'Ceuta');
INSERT INTO `provincias` (`id`,`Nombre`) VALUES ('52', 'Melilla');